// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkqurlugivgaomylodxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrcXVybHVnaXZnYW9teWxvZHhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNDAxMDIsImV4cCI6MjA2NDgxNjEwMn0.5CaXY-3VMMGxb5WgDjy_kVUqDKXYubvFstXKWbIFAcw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);